<a href="https://colab.research.google.com/github/thisishasan/speech_processing/blob/main/assignment_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [112]:
!pip -q install opensmile

In [113]:
!pip -q install pyannote.audio

In [114]:
import torch

In [115]:
from pyannote.audio import Pipeline
from pyannote.audio.pipelines.utils.hook import ProgressHook

In [116]:
HUGGINGFACE_ACCESS_TOKEN = ''

In [117]:
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization-community-1", token=HUGGINGFACE_ACCESS_TOKEN)

In [118]:
AUDIO_PATH = "/content/voice_assignment_01.wav"

In [119]:
diarization = pipeline(AUDIO_PATH)

/usr/local/lib/python3.12/dist-packages/pyannote/audio/models/blocks/pooling.py:103: UserWarning: std(): degrees of freedom is <= 0. Correction should be strictly less than the reduction factor (input numel divided by output numel). (Triggered internally at /pytorch/aten/src/ATen/native/ReduceOps.cpp:1857.)
  std = sequences.std(dim=-1, correction=1)

In [120]:
segments = []
for turn, speaker in diarization.speaker_diarization:
    segments.append({
        "start": turn.start,
        "end": turn.end,
        "duration": turn.end - turn.start,
        "speaker": speaker
    })

In [121]:
import pandas as pd

In [122]:
df_segments = pd.DataFrame(segments)
df_segments

       start        end  duration     speaker
0   0.891594   5.127219  4.235625  SPEAKER_00
1   5.785344   7.860969  2.075625  SPEAKER_00
2   8.316594  11.286594  2.970000  SPEAKER_00
3  11.708469  12.805344  1.096875  SPEAKER_00
4  12.855969  13.733469  0.877500  SPEAKER_00

In [123]:
speaker_durations = df_segments.groupby("speaker")["duration"].sum()
speaker_durations

speaker
SPEAKER_00    11.255625
Name: duration, dtype: float64

In [124]:
target_speaker = speaker_durations.idxmax()
target_speaker

'SPEAKER_00'

In [125]:
speaker_rows = df_segments[df_segments["speaker"] == target_speaker]
speaker_rows

       start        end  duration     speaker
0   0.891594   5.127219  4.235625  SPEAKER_00
1   5.785344   7.860969  2.075625  SPEAKER_00
2   8.316594  11.286594  2.970000  SPEAKER_00
3  11.708469  12.805344  1.096875  SPEAKER_00
4  12.855969  13.733469  0.877500  SPEAKER_00

In [126]:
import soundfile as sf

In [127]:
audio, sr = sf.read(AUDIO_PATH)

In [128]:
chunks = []
for _, row in speaker_rows.iterrows():
    start_sample = int(row["start"] * sr)
    end_sample = int(row["end"] * sr)
    chunks.append(audio[start_sample:end_sample])
chunks

[array([-0.30923462, -0.26391602, -0.22930908, ..., -0.20526123,
        -0.09106445, -0.11508179], shape=(186791,)),
 array([ 0.19824219,  0.26144409,  0.27767944, ..., -0.03610229,
         0.11602783,  0.12564087], shape=(91535,)),
 array([0.05093384, 0.08685303, 0.07015991, ..., 0.37567139, 0.35443115,
        0.34118652], shape=(130977,)),
 array([-0.04827881, -0.09591675, -0.12686157, ..., -0.51867676,
        -0.51965332, -0.53787231], shape=(48372,)),
 array([0.02520752, 0.03997803, 0.02386475, ..., 0.14172363, 0.04959106,
        0.02151489], shape=(38697,))]

In [129]:
import numpy as np

In [130]:
speaker_audio = np.concatenate(chunks)
speaker_audio

array([-0.30923462, -0.26391602, -0.22930908, ...,  0.14172363,
        0.04959106,  0.02151489], shape=(496372,))

In [131]:
SPEAKER_FILE = "/content/speaker_segment.wav"

In [132]:
sf.write(SPEAKER_FILE, speaker_audio, sr)

In [133]:
import opensmile

In [134]:
smile = opensmile.Smile(
    feature_set=opensmile.FeatureSet.eGeMAPSv02,
    feature_level=opensmile.FeatureLevel.LowLevelDescriptors
)

In [135]:
mfcc_df = smile.process_file(SPEAKER_FILE)
mfcc_df

                                                                               Loudness_sma3  \
file                         start                  end
/content/speaker_segment.wav 0 days 00:00:00        0 days 00:00:00.020000          2.599372
                             0 days 00:00:00.010000 0 days 00:00:00.030000          3.011721
                             0 days 00:00:00.020000 0 days 00:00:00.040000          3.324730
                             0 days 00:00:00.030000 0 days 00:00:00.050000          3.483802
                             0 days 00:00:00.040000 0 days 00:00:00.060000          3.852622
...                                                                                      ...
                             0 days 00:00:11.160000 0 days 00:00:11.180000          3.075482
                             0 days 00:00:11.170000 0 days 00:00:11.190000          2.888193
                             0 days 00:00:11.180000 0 days 00:00:11.200000          2.840340
                             0 days 00:00:11.190000 0 days 00:00:11.210000          2.784528
                             0 days 00:00:11.200000 0 days 00:00:11.255600907       2.735713

                                                                               alphaRatio_sma3  \
file                         start                  end
/content/speaker_segment.wav 0 days 00:00:00        0 days 00:00:00.020000          -14.248620
                             0 days 00:00:00.010000 0 days 00:00:00.030000          -11.730476
                             0 days 00:00:00.020000 0 days 00:00:00.040000           -9.016803
                             0 days 00:00:00.030000 0 days 00:00:00.050000          -10.726100
                             0 days 00:00:00.040000 0 days 00:00:00.060000           -9.452489
...                                                                                        ...
                             0 days 00:00:11.160000 0 days 00:00:11.180000          -14.430039
                             0 days 00:00:11.170000 0 days 00:00:11.190000          -15.219157
                             0 days 00:00:11.180000 0 days 00:00:11.200000          -15.234216
                             0 days 00:00:11.190000 0 days 00:00:11.210000          -15.452985
                             0 days 00:00:11.200000 0 days 00:00:11.255600907       -15.688198

                                                                               hammarbergIndex_sma3  \
file                         start                  end
/content/speaker_segment.wav 0 days 00:00:00        0 days 00:00:00.020000                26.292269
                             0 days 00:00:00.010000 0 days 00:00:00.030000                22.951645
                             0 days 00:00:00.020000 0 days 00:00:00.040000                17.174456
                             0 days 00:00:00.030000 0 days 00:00:00.050000                16.875282
                             0 days 00:00:00.040000 0 days 00:00:00.060000                13.728139
...                                                                                             ...
                             0 days 00:00:11.160000 0 days 00:00:11.180000                25.422201
                             0 days 00:00:11.170000 0 days 00:00:11.190000                26.843176
                             0 days 00:00:11.180000 0 days 00:00:11.200000                27.811241
                             0 days 00:00:11.190000 0 days 00:00:11.210000                27.026337
                             0 days 00:00:11.200000 0 days 00:00:11.255600907             26.331686

                                                                               slope0-500_sma3  \
file                         start                  end
/content/speaker_segment.wav 0 days 00:00:00        0 days 00:00:00.020000           -0.106951
                             0 days 00:00:00.010000 0 days 00:00:00.030000           -0.108821
                             0 days 00:00:00.020000 0 days 00:00:00.040000           -0.097621
                             0 days 00:00:00.030000 0 days 00:00:00.050000           -0.093628
                             0 days 00:00:00.040000 0 days 00:00:00.060000           -0.067484
...                                                                                        ...
                             0 days 00:00:11.160000 0 days 00:00:11.180000           -0.051976
                             0 days 00:00:11.170000 0 days 00:00:11.190000           -0.059383
                             0 days 00:00:11.180000 0 days 00:00:11.200000           -0.058496
                             0 days 00:00:11.190000 0 days 00:00:11.210000           -0.060877
                             0 days 00:00:11.200000 0 days 00:00:11.255600907        -0.060406

                                                                               slope500-1500_sma3  \
file                         start                  end
/content/speaker_segment.wav 0 days 00:00:00        0 days 00:00:00.020000              -0.016501
                             0 days 00:00:00.010000 0 days 00:00:00.030000              -0.016300
                             0 days 00:00:00.020000 0 days 00:00:00.040000              -0.021592
                             0 days 00:00:00.030000 0 days 00:00:00.050000              -0.018971
                             0 days 00:00:00.040000 0 days 00:00:00.060000              -0.024498
...                                                                                           ...
                             0 days 00:00:11.160000 0 days 00:00:11.180000              -0.012652
                             0 days 00:00:11.170000 0 days 00:00:11.190000              -0.010247
                             0 days 00:00:11.180000 0 days 00:00:11.200000              -0.012264
                             0 days 00:00:11.190000 0 days 00:00:11.210000              -0.012690
                             0 days 00:00:11.200000 0 days 00:00:11.255600907           -0.015312

                                                                               spectralFlux_sma3  \
file                         start                  end
/content/speaker_segment.wav 0 days 00:00:00        0 days 00:00:00.020000              1.437693
                             0 days 00:00:00.010000 0 days 00:00:00.030000              2.939253
                             0 days 00:00:00.020000 0 days 00:00:00.040000              4.043886
                             0 days 00:00:00.030000 0 days 00:00:00.050000              4.800089
                             0 days 00:00:00.040000 0 days 00:00:00.060000              5.995529
...                                                                                          ...
                             0 days 00:00:11.160000 0 days 00:00:11.180000              3.130647
                             0 days 00:00:11.170000 0 days 00:00:11.190000              3.343800
                             0 days 00:00:11.180000 0 days 00:00:11.200000              3.376992
                             0 days 00:00:11.190000 0 days 00:00:11.210000              3.644966
                             0 days 00:00:11.200000 0 days 00:00:11.255600907           4.473384

                                                                               mfcc1_sma3  \
file                         start                  end
/content/speaker_segment.wav 0 days 00:00:00        0 days 00:00:00.020000      15.867073
                             0 days 00:00:00.010000 0 days 00:00:00.030000      13.287300
                             0 days 00:00:00.020000 0 days 00:00:00.040000      10.651544
                             0 days 00:00:00.030000 0 days 00:00:00.050000      11.826164
                             0 days 00:00:00.040000 0 days 00:00:00.060000      15.191737
...                                                                                   ...
                             0 days 00:00:11.160000 0 days 00:00:11.180000      19.048615
                             0 days 00:00:11.170000 0 days 00:00:11.190000      17.919294
                             0 days 00:00:11.180000 0 days 00:00:11.200000      19.001078
                             0 days 00:00:11.190000 0 days 00:00:11.210000      19.152946
                             0 days 00:00:11.200000 0 days 00:00:11.255600907   19.498991

                                                                               mfcc2_sma3  \
file                         start                  end
/content/speaker_segment.wav 0 days 00:00:00        0 days 00:00:00.020000       5.467865
                             0 days 00:00:00.010000 0 days 00:00:00.030000       4.789742
                             0 days 00:00:00.020000 0 days 00:00:00.040000       5.522658
                             0 days 00:00:00.030000 0 days 00:00:00.050000       8.116031
                             0 days 00:00:00.040000 0 days 00:00:00.060000       8.166907
...                                                                                   ...
                             0 days 00:00:11.160000 0 days 00:00:11.180000      14.208511
                             0 days 00:00:11.170000 0 days 00:00:11.190000      15.223895
                             0 days 00:00:11.180000 0 days 00:00:11.200000      17.093824
                             0 days 00:00:11.190000 0 days 00:00:11.210000      18.520906
                             0 days 00:00:11.200000 0 days 00:00:11.255600907   19.140955

                                                                               mfcc3_sma3  \
file                         start                  end
/content/speaker_segment.wav 0 days 00:00:00        0 days 00:00:00.020000       1.105687
                             0 days 00:00:00.010000 0 days 00:00:00.030000       5.200239
                             0 days 00:00:00.020000 0 days 00:00:00.040000       9.800366
                             0 days 00:00:00.030000 0 days 00:00:00.050000      10.860732
                             0 days 00:00:00.040000 0 days 00:00:00.060000      14.929004
...                                                                                   ...
                             0 days 00:00:11.160000 0 days 00:00:11.180000       5.574369
                             0 days 00:00:11.170000 0 days 00:00:11.190000       6.471470
                             0 days 00:00:11.180000 0 days 00:00:11.200000       4.708181
                             0 days 00:00:11.190000 0 days 00:00:11.210000       3.784024
                             0 days 00:00:11.200000 0 days 00:00:11.255600907    2.369398

                                                                               mfcc4_sma3  \
file                         start                  end
/content/speaker_segment.wav 0 days 00:00:00        0 days 00:00:00.020000      12.180123
                             0 days 00:00:00.010000 0 days 00:00:00.030000      15.233991
                             0 days 00:00:00.020000 0 days 00:00:00.040000      18.414421
                             0 days 00:00:00.030000 0 days 00:00:00.050000      22.416449
                             0 days 00:00:00.040000 0 days 00:00:00.060000      24.464111
...                                                                                   ...
                             0 days 00:00:11.160000 0 days 00:00:11.180000       6.645814
                             0 days 00:00:11.170000 0 days 00:00:11.190000      10.317534
                             0 days 00:00:11.180000 0 days 00:00:11.200000      11.940648
                             0 days 00:00:11.190000 0 days 00:00:11.210000       9.686574
                             0 days 00:00:11.200000 0 days 00:00:11.255600907    7.887407

                                                                               ...  \
file                         start                  end                        ...
/content/speaker_segment.wav 0 days 00:00:00        0 days 00:00:00.020000     ...
                             0 days 00:00:00.010000 0 days 00:00:00.030000     ...
                             0 days 00:00:00.020000 0 days 00:00:00.040000     ...
                             0 days 00:00:00.030000 0 days 00:00:00.050000     ...
                             0 days 00:00:00.040000 0 days 00:00:00.060000     ...
...                                                                            ...
                             0 days 00:00:11.160000 0 days 00:00:11.180000     ...
                             0 days 00:00:11.170000 0 days 00:00:11.190000     ...
                             0 days 00:00:11.180000 0 days 00:00:11.200000     ...
                             0 days 00:00:11.190000 0 days 00:00:11.210000     ...
                             0 days 00:00:11.200000 0 days 00:00:11.255600907  ...

                                                                               logRelF0-H1-A3_sma3nz  \
file                         start                  end
/content/speaker_segment.wav 0 days 00:00:00        0 days 00:00:00.020000                  0.000000
                             0 days 00:00:00.010000 0 days 00:00:00.030000                  0.000000
                             0 days 00:00:00.020000 0 days 00:00:00.040000                  3.812435
                             0 days 00:00:00.030000 0 days 00:00:00.050000                  2.495378
                             0 days 00:00:00.040000 0 days 00:00:00.060000                  1.554526
...                                                                                              ...
                             0 days 00:00:11.160000 0 days 00:00:11.180000                 31.872171
                             0 days 00:00:11.170000 0 days 00:00:11.190000                 32.873913
                             0 days 00:00:11.180000 0 days 00:00:11.200000                 32.896885
                             0 days 00:00:11.190000 0 days 00:00:11.210000               -111.124779
                             0 days 00:00:11.200000 0 days 00:00:11.255600907            -175.780594

                                                                               F1frequency_sma3nz  \
file                         start                  end
/content/speaker_segment.wav 0 days 00:00:00        0 days 00:00:00.020000             527.358643
                             0 days 00:00:00.010000 0 days 00:00:00.030000             496.027832
                             0 days 00:00:00.020000 0 days 00:00:00.040000             452.472656
                             0 days 00:00:00.030000 0 days 00:00:00.050000             397.048950
                             0 days 00:00:00.040000 0 days 00:00:00.060000             353.843140
...                                                                                           ...
                             0 days 00:00:11.160000 0 days 00:00:11.180000             764.988770
                             0 days 00:00:11.170000 0 days 00:00:11.190000             976.525574
                             0 days 00:00:11.180000 0 days 00:00:11.200000             992.085510
                             0 days 00:00:11.190000 0 days 00:00:11.210000            1064.503174
                             0 days 00:00:11.200000 0 days 00:00:11.255600907         1037.506836

                                                                               F1bandwidth_sma3nz  \
file                         start                  end
/content/speaker_segment.wav 0 days 00:00:00        0 days 00:00:00.020000            1124.301147
                             0 days 00:00:00.010000 0 days 00:00:00.030000            1019.470642
                             0 days 00:00:00.020000 0 days 00:00:00.040000             931.495544
                             0 days 00:00:00.030000 0 days 00:00:00.050000            1177.627808
                             0 days 00:00:00.040000 0 days 00:00:00.060000            1252.889771
...                                                                                           ...
                             0 days 00:00:11.160000 0 days 00:00:11.180000            1127.003174
                             0 days 00:00:11.170000 0 days 00:00:11.190000             944.981628
                             0 days 00:00:11.180000 0 days 00:00:11.200000             915.955994
                             0 days 00:00:11.190000 0 days 00:00:11.210000            1059.803589
                             0 days 00:00:11.200000 0 days 00:00:11.255600907         1020.648743

                                                                               F1amplitudeLogRelF0_sma3nz  \
file                         start                  end
/content/speaker_segment.wav 0 days 00:00:00        0 days 00:00:00.020000                    -201.000000
                             0 days 00:00:00.010000 0 days 00:00:00.030000                    -137.920120
                             0 days 00:00:00.020000 0 days 00:00:00.040000                     -73.983360
                             0 days 00:00:00.030000 0 days 00:00:00.050000                     -10.475046
                             0 days 00:00:00.040000 0 days 00:00:00.060000                       0.000000
...                                                                                                   ...
                             0 days 00:00:11.160000 0 days 00:00:11.180000                     -13.540906
                             0 days 00:00:11.170000 0 days 00:00:11.190000                     -15.155618
                             0 days 00:00:11.180000 0 days 00:00:11.200000                     -13.644216
                             0 days 00:00:11.190000 0 days 00:00:11.210000                     -18.401018
                             0 days 00:00:11.200000 0 days 00:00:11.255600907                  -19.706493

                                                                               F2frequency_sma3nz  \
file                         start                  end
/content/speaker_segment.wav 0 days 00:00:00        0 days 00:00:00.020000            1610.974976
                             0 days 00:00:00.010000 0 days 00:00:00.030000            1555.148804
                             0 days 00:00:00.020000 0 days 00:00:00.040000            1504.174194
                             0 days 00:00:00.030000 0 days 00:00:00.050000            1524.340942
                             0 days 00:00:00.040000 0 days 00:00:00.060000            1508.280762
...                                                                                           ...
                             0 days 00:00:11.160000 0 days 00:00:11.180000            1855.025391
                             0 days 00:00:11.170000 0 days 00:00:11.190000            2172.257812
                             0 days 00:00:11.180000 0 days 00:00:11.200000            2177.593506
                             0 days 00:00:11.190000 0 days 00:00:11.210000            2236.126221
                             0 days 00:00:11.200000 0 days 00:00:11.255600907         2251.777344

                                                                               F2bandwidth_sma3nz  \
file                         start                  end
/content/speaker_segment.wav 0 days 00:00:00        0 days 00:00:00.020000            1269.999146
                             0 days 00:00:00.010000 0 days 00:00:00.030000             881.605469
                             0 days 00:00:00.020000 0 days 00:00:00.040000             469.408844
                             0 days 00:00:00.030000 0 days 00:00:00.050000             601.972351
                             0 days 00:00:00.040000 0 days 00:00:00.060000             615.505676
...                                                                                           ...